{
  "development": {
    "username": "djamware",
    "password": "dj@mw@r3",
    "database": "${app.shortName}",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "test": {
    "username": "root",
    "password": "dj@mw@r3",
    "database": "${app.shortName}",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "production": {
    "username": "root",
    "password": "dj@mw@r3",
    "database": "${app.shortName}",
    "host": "127.0.0.1",
    "dialect": "postgres"
  }
}
